### ISSUE TITLE
Error on automatic renewal when the user has agreed to be notified by Vipps

### ISSUE THREAD

**Issue by cwitkonsult** [vippsas/vipps-recurring-api#86]
During the automatic renewal, the payment fails if the user has agreed to be notified before the payment on the Vipps app. 

The payment goes through and are successfully withdrawn from the users bank account and also received on the business bank account. But the message Woocommerce revieves from Vipps is that the payment fails. The subscription is ‘on-hold’ and the user wont be able to log in.

**Comment by cloveras** [comment]
Hi

Thanks for reporting this! We have just now received a similar issue from another customer. Our partner, Everyday, who has imnplemented the plugin will follow up.

If you have something else to report, the plugin's repository is here: https://github.com/vippsas/vipps-recurring-woocommerce (we will of course manage this issue even if it's technically not in the right repo)

Christian, Vipps

**Comment by Marcuzz** [comment]
Hi,

I am not entirely sure if the issue you're having is related to a failed payment or not. Usually when a payment fails the status would be `failed` instead of `on-hold` in WooCommerce. There are a few things you can do to debug this:

1. There's a menu area in Settings -> Vipps Recurring Payments where you can check the status of an individual order, can you do this for the order in question?

2. To prevent renewals from going `on-hold` for subscription services where an `on-hold` status means access being temporarily revoked, we have added a setting called `Default status to give pending renewals`, for your use case you want to set this to either `Processing` or `Completed`.

What I actually think happens here is that WordPress' task scheduler is not fast enough at checking the pending Vipps transactions as it only does so whenever someone visits the site, and for performance reasons it can only check a few transactions at a time. This is why the area in (1.) exists.

I hope this helps you debug the issue further, please get back to me either in this issue, or here: https://github.com/vippsas/vipps-recurring-woocommerce/issues/18. Alternatively we could communicate by email at vipps@everyday.no 😄 

Marcus,
Everyday

**Comment by cloveras** [comment]
Hi @cwitkonsult 

Does the above answer your question, so we can close this issue!

Christian, Vipps
